#!/usr/local/bin/fish
#Author: Miguel Pérez Ontiveros

# Check if the type of test was provided
if [ (count $argv) -lt 1 ]
	echo "you must supply the type of test you want and optionally a name for your test's folder."
	exit
end

if not [ -d "src/"$argv[1] ]
	echo "test not supported"
	exit
end

set folder "Tests_"$argv[1]

# Create folder
if [ (count $argv) -gt 1 ]
	set subfolder $argv[2]
else
	set subfolder 'test'
end
if [ -d $folder"/"$subfolder ]
    set i 1
    while [ -d $folder"/"$subfolder$i ]
        set i (math "$i+1")
    end
    set subfolder $subfolder$i
end
mkdir -p $folder"/"$subfolder

# copy source files (1.-start.sh 2.-run.sh 3.-language's main file)
cp src"/"$argv[1]/* $folder"/"$subfolder

# cd to test's folder
cd $folder"/"$subfolder

#chmod the sh's
chmod +x *.sh

# open folder on sublime
sublime .

# start
if [ -e start.sh ]
	./start.sh
end
